SQLALCHEMY_DATABASE_URI = 'mysql://root:123456@127.0.0.1/gaokao'
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf-8"
DEBUG = True
SERVER_PORT = 8999
JSON_AS_ASCII = False